import {accountRuntime,currentSession} from "@/accounts/runtime";
import {AccountError,authorizedRepository} from "@/accounts/github";
import {unseal,validMutation} from "@/accounts/security";
import type {ImpactReport} from "@/engine/types";
export const privateHeaders={"Cache-Control":"private, no-store"};
export async function workspaceAccess(request?:Request){const runtime=await accountRuntime();if(request&&!validMutation(request,runtime.origin))throw new AccountError(403,"This request is not allowed.");const session=await currentSession(runtime);if(!session)throw new AccountError(401,"Sign in to continue.");return {runtime,session};}
export async function readInput(request:Request,limit=4096){const reader=request.body?.getReader();if(!reader)throw new AccountError(400,"Missing input.");let size=0,text="";const decoder=new TextDecoder();for(;;){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>limit){await reader.cancel();throw new AccountError(413,"Input is too large.");}text+=decoder.decode(value,{stream:true});}try{return JSON.parse(text+decoder.decode()) as Record<string,unknown>;}catch{throw new AccountError(400,"Invalid input.");}}
export function workspaceError(error:unknown){return Response.json({message:error instanceof AccountError?error.message:"The workspace is unavailable. Please try again."},{status:error instanceof AccountError?error.status:503,headers:privateHeaders});}
export async function reviewAccess(id:string){const {runtime,session}=await workspaceAccess();const row=await runtime.db.prepare("SELECT * FROM workspace_reviews WHERE id=? AND expires_at>? AND (github_id=? OR EXISTS(SELECT 1 FROM workspace_shares WHERE review_id=workspace_reviews.id AND github_id=?))").bind(id,Date.now(),session.githubId,session.githubId).first<{github_id:number;installation_id:number;repo_id:number;report_cipher:string;owner:string;repo:string;pr_number:number;head_sha:string;base_sha:string;created_at:number}>();if(!row)throw new AccountError(404,"This review is unavailable or has expired.");const repo=await authorizedRepository(session.token,row.installation_id,row.repo_id,runtime.slug);if(repo.private&&!runtime.privateRepositories)throw new AccountError(403,"Private repositories are unavailable.");const report=unseal<ImpactReport>(row.report_cipher,runtime.secret);if(!report)throw new AccountError(404,"Review unavailable.");return {runtime,session,row,report};}
