import {beforeAll,afterAll,beforeEach,describe,it,expect,vi} from "vitest";
import {Miniflare,convertV4MiniflareOptions} from "miniflare";
import {readFile} from "node:fs/promises";
import {createHmac} from "node:crypto";
import type {AccountRuntime} from "@/accounts/runtime";
import type {D1Database} from "@cloudflare/workers-types";
import {analyze} from "@/engine";
import {authMigration} from "@/engine/fixtures";
import {unseal} from "@/accounts/security";
import {parsePullUrl,findings,comparison} from "./model";
const mocks=vi.hoisted(()=>({send:vi.fn(),authorized:vi.fn(),github:vi.fn(),snapshot:vi.fn(),runtime:vi.fn(),session:vi.fn(),mint:vi.fn()}));
vi.mock("@opennextjs/cloudflare",()=>({getCloudflareContext:async()=>({env:{WORKSPACE_QUEUE:{send:mocks.send}}})}));
vi.mock("@/accounts/runtime",()=>({accountRuntime:mocks.runtime,currentSession:mocks.session}));
vi.mock("@/accounts/github",async original=>({...await original<typeof import("@/accounts/github")>(),authorizedRepository:mocks.authorized,github:mocks.github}));
vi.mock("@/github/retrieval",async original=>({...await original<typeof import("@/github/retrieval")>(),githubSnapshotProvider:()=>mocks.snapshot}));
vi.mock("@/github/app-auth",()=>({mintInstallationToken:mocks.mint}));
import {createJob,executeJob} from "./jobs";
import {GET as feedbackGet,POST as feedbackPost} from "@/app/api/workspace/feedback/[id]/route";
import {POST as preferencesPost} from "@/app/api/workspace/preferences/route";
import {GET as jobGet} from "@/app/api/workspace/jobs/[id]/route";
import {POST as webhookPost} from "@/app/api/workspace/github/route";
import {GitHubApiError} from "@/github/retrieval";
let mf:Miniflare,db:D1Database,runtime:AccountRuntime;
const session={githubId:42,login:"tester",token:"test-token-not-real"};
const secret="test-only-encryption-key-with-32-characters";
const selection={installation:1,repository:2,pull:3};
beforeAll(async()=>{mf=new Miniflare(convertV4MiniflareOptions({modules:true,script:"export default {fetch(){return new Response('test')}}",compatibilityDate:"2026-10-08",d1Databases:{WAITLIST_DB:"test-workspace-db"}}));db=await mf.getD1Database("WAITLIST_DB") as unknown as D1Database;for(const file of ["0003_accounts.sql","0004_workspace.sql","0005_job_leases.sql"]){const text=await readFile(`d1/migrations/${file}`,"utf8");for(const statement of text.split(";"))if(statement.trim())await db.prepare(statement).run();}runtime={origin:"https://nodedots.com",clientId:"test",clientSecret:"test",slug:"nodedots-code",secret,privateRepositories:false,db,ready:true,appId:"",privateKey:"",webhookSecret:"",runnerSecret:""};},60000);
afterAll(async()=>{await mf?.dispose();});
beforeEach(async()=>{vi.clearAllMocks();await db.batch([db.prepare("DELETE FROM workspace_feedback"),db.prepare("DELETE FROM workspace_reviews"),db.prepare("DELETE FROM workspace_jobs"),db.prepare("DELETE FROM workspace_automation"),db.prepare("DELETE FROM account_rate_limits")]);mocks.runtime.mockResolvedValue(runtime);mocks.session.mockResolvedValue(session);mocks.send.mockResolvedValue(undefined);mocks.authorized.mockResolvedValue({id:2,name:"repo",owner:{login:"owner"},private:false});mocks.github.mockResolvedValue({title:"Migrate identity",head:{sha:"head",repo:{name:"repo",owner:{login:"owner"},fork:false}},base:{sha:"base"}});mocks.snapshot.mockResolvedValue(authMigration());});
function mutation(body:unknown,origin="https://nodedots.com"){return new Request("https://nodedots.com/api/workspace",{method:"POST",headers:{origin,"Content-Type":"application/json"},body:JSON.stringify(body)});}
describe("workspace workflow",()=>{
 it("accepts only canonical GitHub PR URLs",()=>{expect(parsePullUrl("https://github.com/owner/repo/pull/3")).toEqual({owner:"owner",repo:"repo",pull:3});for(const bad of ["https://github.com.evil/owner/repo/pull/3","https://user:pass@github.com/owner/repo/pull/3","http://github.com/owner/repo/pull/3","https://github.com/owner/repo/issues/3"])expect(parsePullUrl(bad)).toBeNull();});
 it("queues once for repeated requests to the same captured commits",async()=>{const id=await createJob(runtime,session,selection);expect(await createJob(runtime,session,selection)).toBe(id);expect(mocks.send).toHaveBeenCalledTimes(1);const row=await db.prepare("SELECT token_cipher FROM workspace_jobs WHERE id=?").bind(id).first<{token_cipher:string}>();expect(row?.token_cipher).not.toContain(session.token);expect(unseal(row!.token_cipher,secret)).toBe(session.token);});
 it("persists a pinned report, erases the queued credential, and ignores duplicate delivery",async()=>{const id=await createJob(runtime,session,selection);expect(await executeJob(runtime,id)).toBe("done");const row=await db.prepare("SELECT status,stage,review_id,token_cipher FROM workspace_jobs WHERE id=?").bind(id).first();expect(row).toMatchObject({status:"completed",stage:"completed",review_id:id,token_cipher:null});const stored=await db.prepare("SELECT report_cipher FROM workspace_reviews WHERE id=?").bind(id).first<{report_cipher:string}>();expect(findings(unseal(stored!.report_cipher,secret)!)).not.toHaveLength(0);await executeJob(runtime,id);expect(mocks.snapshot).toHaveBeenCalledTimes(1);});
 it("does not publish a report if access is revoked during analysis",async()=>{const id=await createJob(runtime,session,selection);mocks.authorized.mockResolvedValueOnce({id:2}).mockRejectedValueOnce(new Error("revoked"));await executeJob(runtime,id);expect(await db.prepare("SELECT id FROM workspace_reviews WHERE id=?").bind(id).first()).toBeNull();expect(await db.prepare("SELECT status,token_cipher FROM workspace_jobs WHERE id=?").bind(id).first()).toMatchObject({status:"failed",token_cipher:null});});
 it("rejects superseded snapshots instead of mixing a new file list with old commits",async()=>{const id=await createJob(runtime,session,selection);mocks.github.mockResolvedValue({head:{sha:"new-head",repo:{name:"repo",owner:{login:"owner"},fork:false}},base:{sha:"base"}});await executeJob(runtime,id);expect(mocks.snapshot).not.toHaveBeenCalled();expect(await db.prepare("SELECT status FROM workspace_jobs WHERE id=?").bind(id).first()).toMatchObject({status:"failed"});});
 it("saves decisions with a reason and blocks cross-user reads and forged fingerprints",async()=>{const id=await createJob(runtime,session,selection);await executeJob(runtime,id);const report=await analyze(authMigration(),{enrichment:false}),fingerprint=findings(report)[0].fingerprint,params={params:Promise.resolve({id})};expect((await feedbackPost(mutation({fingerprint,disposition:"accepted",reason:"Needs migration"}),params)).status).toBe(200);const saved=await (await feedbackGet(new Request("https://nodedots.com"),params)).json();expect(saved.events[0]).toMatchObject({fingerprint,disposition:"accepted",reason:"Needs migration"});expect((await feedbackPost(mutation({fingerprint:"forged",disposition:"fixed",reason:""}),params)).status).toBe(400);expect((await feedbackPost(mutation({fingerprint,disposition:"fixed",reason:""},"https://evil.test"),params)).status).toBe(403);mocks.session.mockResolvedValue({...session,githubId:99});expect((await feedbackGet(new Request("https://nodedots.com"),params)).status).toBe(404);expect((await jobGet(new Request("https://nodedots.com"),params)).status).toBe(404);});
 it("requires configured app credentials and maintainer rights for automation",async()=>{expect((await preferencesPost(mutation({...selection,automatic:true}))).status).toBe(503);mocks.runtime.mockResolvedValue({...runtime,appId:"1",privateKey:"test",webhookSecret:"test"});mocks.github.mockResolvedValue({permissions:{admin:false,maintain:false}});expect((await preferencesPost(mutation({...selection,automatic:true}))).status).toBe(403);expect(await db.prepare("SELECT * FROM workspace_automation").first()).toBeNull();});
 it("compares observations without calling disappearance a fix",async()=>{const report=await analyze(authMigration());expect(comparison(report,report)).toMatchObject({new:0,noLongerObserved:0});expect(comparison({...report,missing:[],conflicting:[],uncertain:[],untested:[],actionRequired:[]},report).noLongerObserved).toBe(findings(report).length);});
 it("does not retain a queued credential when the queue rejects delivery",async()=>{mocks.send.mockRejectedValueOnce(new Error("unavailable"));await expect(createJob(runtime,session,selection)).rejects.toThrow();expect(await db.prepare("SELECT status,token_cipher FROM workspace_jobs").first()).toMatchObject({status:"failed",token_cipher:null});});
 it("authenticates signed events, respects opt-in, and deduplicates automatic reviews",async()=>{
  const configured={...runtime,appId:"app",privateKey:"test-key",webhookSecret:"test-webhook-secret"};mocks.runtime.mockResolvedValue(configured);mocks.mint.mockResolvedValue({token:"installation-test-token"});
  const raw=JSON.stringify({action:"synchronize",installation:{id:1},repository:{id:2,full_name:"owner/repo",private:false},pull_request:{number:3,draft:false}});
  const delivery=(id:string,signature=true)=>new Request("https://nodedots.com/api/workspace/github",{method:"POST",headers:{"x-github-event":"pull_request","x-github-delivery":id,"x-hub-signature-256":signature?`sha256=${createHmac("sha256",configured.webhookSecret).update(raw).digest("hex")}`:"sha256=bad"},body:raw});
  expect((await webhookPost(delivery("bad",false))).status).toBe(401);expect(mocks.send).not.toHaveBeenCalled();
  expect((await webhookPost(delivery("ignored"))).status).toBe(202);expect(mocks.send).not.toHaveBeenCalled();
  await db.prepare("INSERT INTO workspace_automation(github_id,installation_id,repo_id,enabled,updated_at) VALUES(42,1,2,1,0)").run();
  mocks.github.mockImplementation(async(_token:string,path:string)=>path.endsWith("/pulls/3")?{title:"Change",head:{sha:"head"},base:{sha:"base"}}:{id:2,private:false});
  expect((await webhookPost(delivery("enabled"))).status).toBe(202);expect((await webhookPost(delivery("enabled"))).status).toBe(200);expect(mocks.send).toHaveBeenCalledTimes(1);expect(await db.prepare("SELECT automatic,token_cipher FROM workspace_jobs").first()).toMatchObject({automatic:1,token_cipher:null});
 });
 it("checks automation is still enabled before a queued automatic job executes",async()=>{const id=await createJob(runtime,session,selection,true);await executeJob(runtime,id);expect(mocks.snapshot).not.toHaveBeenCalled();expect(await db.prepare("SELECT status FROM workspace_jobs WHERE id=?").bind(id).first()).toMatchObject({status:"failed"});});
 it("backs off transient GitHub failures and completes the same job on redelivery",async()=>{const id=await createJob(runtime,session,selection);mocks.snapshot.mockRejectedValueOnce(new GitHubApiError(503,"upstream"));expect(await executeJob(runtime,id)).toBe("busy");expect(await db.prepare("SELECT status,attempts FROM workspace_jobs WHERE id=?").bind(id).first()).toMatchObject({status:"queued",attempts:1});expect(await executeJob(runtime,id)).toBe("done");expect(await db.prepare("SELECT status,attempts,token_cipher FROM workspace_jobs WHERE id=?").bind(id).first()).toMatchObject({status:"completed",attempts:2,token_cipher:null});});
 it("prevents an old lease from persisting a report or overwriting replacement work",async()=>{const id=await createJob(runtime,session,selection);mocks.snapshot.mockImplementationOnce(async()=>{await db.prepare("UPDATE workspace_jobs SET lease='replacement' WHERE id=?").bind(id).run();return authMigration();});expect(await executeJob(runtime,id)).toBe("busy");expect(await db.prepare("SELECT id FROM workspace_reviews WHERE id=?").bind(id).first()).toBeNull();expect(await db.prepare("SELECT lease,status FROM workspace_jobs WHERE id=?").bind(id).first()).toMatchObject({lease:"replacement",status:"running"});});
});


