"use client";
import {useEffect,useState,useId} from "react";
import {defaultSettings,emptyBrief,type Settings,type Brief,type Check} from "@/shipping/model";
import type {ImpactReport} from "@/engine/types";
import {findings} from "@/workspace/model";
async function request(url:string,input?:unknown,method="POST",signal?:AbortSignal){const response=await fetch(url,{cache:"no-store",signal,...(input?{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(input)}:{})});const body=await response.json();if(!response.ok)throw new Error(body.message??"Could not complete this request.");return body;}
const lines=(value:string)=>value.split("\n").map(s=>s.trim()).filter(Boolean);
function LinesField({label,value,placeholder,onChange}:{label:string;value:string[];placeholder?:string;onChange:(value:string[])=>void}){const joined=value.join("\n"),[draft,setDraft]=useState(joined);useEffect(()=>setDraft(joined),[joined]);return <label>{label}<textarea maxLength={4000} value={draft} placeholder={placeholder} onChange={e=>setDraft(e.target.value)} onBlur={()=>onChange(lines(draft))}/></label>;}
export function ShippingSetup({installation,repository}:{installation:number;repository:number}){
 const [settings,setSettings]=useState<Settings>(defaultSettings),[brief,setBrief]=useState<Brief>(emptyBrief),[pull,setPull]=useState(""),[manage,setManage]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const [health,setHealth]=useState<{verified:boolean;configured:boolean;eventSubscribed:boolean;urlMatches:boolean;lastDelivery:{status:number;at:string}|null}|null>(null),[automatic,setAutomatic]=useState(false);
 const [policyVersion,setPolicyVersion]=useState<number|null>(null),[briefVersion,setBriefVersion]=useState<number|null>(null);
 const url=`/api/workspace/shipping?installation=${installation}&repository=${repository}`;
 useEffect(()=>{const controller=new AbortController();request(url,undefined,"GET",controller.signal).then(data=>{setSettings(data.settings);setPolicyVersion(data.updatedAt);setManage(data.canManage);setHealth(data.health);setAutomatic(data.automatic);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[url]);
 async function save(kind:string){setBusy(true);setError("");setMessage("");try{const result=await request("/api/workspace/shipping",{installation,repository,kind,settings,brief,pull:Number(pull),updatedAt:kind==="brief"?briefVersion:policyVersion});if(kind==="brief")setBriefVersion(result.updatedAt);else setPolicyVersion(result.updatedAt);setMessage(kind==="brief"?"Change intent saved. It will appear in this PR’s shipping review.":"Repository policy saved.");}catch(e){setError(e instanceof Error?e.message:"Could not save.");}finally{setBusy(false);}}
 async function loadBrief(){setBusy(true);setError("");try{const data=await request(`${url}&pull=${Number(pull)}`);setBrief(data.brief??emptyBrief);setBriefVersion(data.updatedAt);setMessage("Brief loaded.");}catch(e){setError(e instanceof Error?e.message:"Could not load.");}finally{setBusy(false);}}
 return <div className="ship-stack"><section className="ws-panel ws-padded"><p className="ws-label">REPOSITORY READINESS</p><h2>Set up the way your team ships.</h2><div className="ship-signals"><Signal label="Repository access" value={health?"Verified through your GitHub App":"Checking current access…"}/><Signal label="App & webhook" value={!health?"Checking…":!health.verified?"Verification unavailable":health.eventSubscribed&&health.urlMatches?"PR events configured":"Configuration needs attention"}/><Signal label="Last PR delivery" value={health?.lastDelivery?`${health.lastDelivery.status} · ${new Date(health.lastDelivery.at).toLocaleString()}`:"No recent PR delivery observed"}/><Signal label="Automatic reviews" value={automatic?"Enabled":"Off · enable in Repository context"}/><Signal label="Analysis coverage" value="JavaScript / TypeScript static relationships; scope recorded per report"/></div><p className="ws-muted">A configured webhook does not prove delivery. Open or update a PR to establish delivery evidence.</p></section>
 <form className="ws-panel ws-padded ship-form" onSubmit={e=>{e.preventDefault();save("settings");}}><p className="ws-label">SHIPPING POLICY</p><h2>Make expectations explicit.</h2><p>Maintainers configure the policy. NodeDots reports each signal and leaves the shipping decision with your team.</p><fieldset disabled={!manage||busy}><div className="ship-fields">{([["criticalPaths","Critical path prefixes","src/auth/\nsrc/billing/"],["requiredChecks","Required CI names (exact match)","build\ntest"],["reviewers","Expected GitHub reviewers","octocat"],["releaseSteps","Team release practices","Verify staging smoke test"]] as const).map(([key,label,placeholder])=><LinesField key={key} label={label} value={settings[key]} placeholder={placeholder} onChange={value=>setSettings(current=>({...current,[key]:value}))}/>)}</div><label>Observation acknowledgment<select value={settings.acknowledge} onChange={e=>setSettings({...settings,acknowledge:e.target.value as Settings["acknowledge"]})}><option value="high">High severity observations</option><option value="all">All observations</option><option value="none">No acknowledgment requirement</option></select></label><button className="clarity-start-button">Save repository policy</button></fieldset>{!manage&&<p className="ws-muted">Repository administrator or maintainer access is required to edit policy.</p>}</form>
 <section className="ws-panel ws-padded ship-form"><p className="ws-label">BEFORE IMPLEMENTATION</p><h2>Write the change intent.</h2><p>Describe the outcome and constraints before reviewing a PR. Acceptance criteria become human-assessed checklist items.</p><label>Pull request number<input type="number" min="1" value={pull} onChange={e=>{setPull(e.target.value);setBrief(emptyBrief);setBriefVersion(null);}}/></label><button className="ws-secondary" disabled={busy||!pull} onClick={loadBrief}>Load existing brief</button><BriefFields brief={brief} onChange={setBrief}/><button className="clarity-start-button" disabled={busy||!pull} onClick={()=>save("brief")}>Save change intent</button></section>{error&&<p role="alert" className="ws-error">{error}</p>}{message&&<p role="status">{message}</p>}</div>;
}
function BriefFields({brief,onChange}:{brief:Brief;onChange:(brief:Brief)=>void}){return <><label>Intended outcome<textarea maxLength={2000} value={brief.outcome} onChange={e=>onChange({...brief,outcome:e.target.value})}/></label><LinesField label="Acceptance criteria · one per line" value={brief.criteria} onChange={criteria=>onChange({...brief,criteria})}/><label>Constraints and non-goals<textarea maxLength={2000} value={brief.constraints} onChange={e=>onChange({...brief,constraints:e.target.value})}/></label></>;}
function Signal({label,value}:{label:string;value:string}){return <div><span className="ws-label">{label}</span><strong>{value}</strong></div>;}
type Item={key:string;label:string;source:string;status?:string;note?:string;actor?:string;at?:number};
type Readiness={decisions:{github_id:number;fingerprint:string;disposition:string;created_at:number}[];head:string;coverage:string;unknowns:number;freshness:string;draft:boolean|null;pullState:string;ci:{checks:Check[];errors:string[];checkedAt:number};requiredChecks:Check[];reviewers:{login:string;state:string}[];reviewersTruncated:boolean;policy:{required:number;acknowledged:number};items:Item[];brief:Brief;shares:{github_id:number;login:string}[];canShare:boolean};
export function ShippingReview({id,report,repository,pull,revision,installation,repoId}:{id:string;report:ImpactReport;repository:string;pull:number;revision:number;installation:number;repoId:number}){
 const [data,setData]=useState<Readiness|null>(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[refresh,setRefresh]=useState(0),[recipient,setRecipient]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{const controller=new AbortController();request(`/api/workspace/shipping/${id}`,undefined,"GET",controller.signal).then(setData).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[id,refresh,revision]);
 async function mutate(url:string,input:unknown,method="POST"){setBusy(true);setError("");setMessage("");try{await request(url,input,method);setRefresh(n=>n+1);setMessage("Saved.");return true;}catch(e){setError(e instanceof Error?e.message:"Could not save.");return false;}finally{setBusy(false);}}
 function handoff(){if(!data)return "";return [`NodeDots reviewer handoff · ${repository} #${pull}`,`Report: ${location.origin}/workspace/reviews/${id}`,`Reviewed head: ${data.head}`,`Freshness: ${data.freshness}; PR: ${data.pullState}${data.draft?" (draft)":""}`,`Coverage: ${data.coverage}; unknown areas: ${data.unknowns}`,`CI observed: ${new Date(data.ci.checkedAt).toISOString()}`,...data.ci.checks.map(c=>`  ${c.name}: ${c.state}${c.url?` · ${c.url}`:""}`),...data.ci.errors,`Required acknowledgments: ${data.policy.acknowledged}/${data.policy.required}`,`Expected reviewers: ${data.reviewers.map(r=>`${r.login}: ${r.state}`).join(", ")||"Not configured"}`,"",`Intent: ${data.brief.outcome||"Not recorded"}`,`Constraints: ${data.brief.constraints||"Not recorded"}`,"",...findings(report).map(f=>`${f.severity} · ${f.title}\n${f.explanation}\nEvidence: ${f.evidence.map(e=>`${e.path}:${e.startLine}`).join(", ")}\nNext: ${f.nextStep}\nDecisions: ${data.decisions?.filter(d=>d.fingerprint===f.fingerprint).map(d=>`GitHub user ${d.github_id}: ${d.disposition}`).join("; ")||"Not recorded"}`),"",...report.unknown.map(u=>`Unknown: ${u.detail}`),"Release preparation (human assessments):",...data.items.map(i=>`${i.label}: ${i.status??"pending"}${i.actor?` · ${i.actor}`:""}${i.note?`\n${i.note}`:""}`),"", "Advisory report. Acknowledgment does not establish a fix. Check live CI and current commits before shipping."].join("\n");}
 async function copy(){try{await navigator.clipboard.writeText(handoff());setMessage("Reviewer handoff copied.");}catch{setError("Clipboard unavailable. Download the handoff instead.");}}
 function download(){const url=URL.createObjectURL(new Blob([handoff()],{type:"text/plain;charset=utf-8"})),anchor=document.createElement("a");anchor.href=url;anchor.download=`nodedots-pr-${pull}-handoff.txt`;anchor.click();URL.revokeObjectURL(url);}
 return <section className="ship-stack"><div className="ws-panel ws-padded"><div className="ws-panel-head"><div><p className="ws-label">SHIP READINESS</p><h2>Evidence for the shipping decision.</h2></div><button className="ws-secondary" onClick={()=>{setError("");setRefresh(n=>n+1);}}>Refresh signals</button></div>{!data?<p role="status">{error?"Readiness could not load.":"Loading current GitHub signals…"}</p>:<><div className="ship-signals"><Signal label="Review freshness" value={`${data.freshness} · ${data.head.slice(0,8)}`}/><Signal label="Scope" value={`${data.coverage} · ${data.unknowns} unknown areas`}/><Signal label="Acknowledgment policy" value={`${data.policy.acknowledged} of ${data.policy.required} recorded`}/><Signal label="Release preparation" value={`${data.items.filter(i=>i.status&&i.status!=="pending").length} of ${data.items.length} assessed`}/></div><p className="ws-muted">Independent signals, observed at {new Date(data.ci.checkedAt).toLocaleString()}. CI belongs to the reviewed commit; refresh or recheck after changes. Human assessments do not prove correctness.</p>{data.freshness!=="current"&&<p className="ws-notice">{data.freshness==="stale"?"Head or base changed. Recheck before using this report to ship.":"Current PR commits could not be verified."}</p>}<div className="ship-fields"><div><h3>GitHub checks</h3>{data.ci.checks.length?data.ci.checks.map((c,i)=><p key={`${c.name}:${i}`} className="ship-check"><span>{c.url?<a href={c.url} target="_blank" rel="noreferrer">{c.name} ↗</a>:c.name}</span><span className="ws-badge">{c.state}</span></p>):<p>No checks observed on this commit.</p>}{data.ci.errors.map(e=><p className="ws-notice" key={e}>{e}</p>)}<h4>Required checks</h4>{data.requiredChecks.length?data.requiredChecks.map(c=><p key={c.name}>{c.name} · {c.state}</p>):<p className="ws-muted">No required check names configured.</p>}</div><div><h3>Expected reviewers</h3>{data.reviewers.length?data.reviewers.map(r=><p key={r.login}>{r.login} · {r.state}</p>):<p>No expected reviewers configured.</p>}{data.reviewersTruncated&&<p className="ws-notice">Review history exceeds this view’s limit. Confirm on GitHub.</p>}<h3>Change intent</h3><p>{data.brief.outcome||"Not recorded. Add an intent brief in Shipping setup."}</p><p className="ws-muted">{data.brief.constraints}</p><a href={`/workspace?view=shipping&installation=${installation}&repository=${repoId}`}>Edit repository policy and intent →</a></div></div></>}</div>
 {data&&<><section className="ws-panel ws-padded"><p className="ws-label">PRE-SHIP CHECKLIST</p><h2>Prepare the release, with context.</h2>{data.items.map(item=><ChecklistRow key={item.key} item={item} busy={busy} onSave={(status,note)=>mutate(`/api/workspace/shipping/${id}`,{key:item.key,status,note})}/>)}</section><section className="ws-panel ws-padded ship-form"><p className="ws-label">REVIEWER HANDOFF</p><h2>Give the next reviewer the connected view.</h2><p>Export the commit, CI snapshot, consequences, evidence, unknowns, and release decisions. The report link requires sign-in and an explicit grant.</p><div className="ws-review-actions"><button className="ws-secondary" onClick={copy}>Copy handoff</button><button className="ws-secondary" onClick={download}>Download handoff</button></div>{data.canShare&&<><label>Share with a GitHub username<input value={recipient} maxLength={39} onChange={e=>setRecipient(e.target.value)} placeholder="octocat"/></label><button className="clarity-start-button" disabled={busy||!recipient.trim()} onClick={async()=>{if(await mutate(`/api/workspace/shares/${id}`,{login:recipient.trim()}))setRecipient("");}}>Grant review access</button><p className="ws-muted">Recipients must also have access to this repository through NodeDots. They can read the report and record their own observations and release assessments. Access expires with the report after 7 days.</p>{data.shares.map(s=><div className="ship-check" key={s.github_id}><span>{s.login}</span><button className="ws-text-button" disabled={busy} onClick={()=>mutate(`/api/workspace/shares/${id}`,{githubId:s.github_id},"DELETE")}>Revoke access</button></div>)}</>}</section></>}{error&&<p role="alert" className="ws-error">{error}</p>}{message&&<p role="status">{message}</p>}</section>;
}
function ChecklistRow({item,busy,onSave}:{item:Item;busy:boolean;onSave:(status:string,note:string)=>Promise<boolean>}){
 const controlId=useId();
 const [status,setStatus]=useState(item.status??"pending"),[note,setNote]=useState(item.note??"");
 useEffect(()=>{setStatus(item.status??"pending");setNote(item.note??"");},[item.status,item.note]);
 return <details className="ship-item"><summary><strong>{item.label}</strong><span className="ws-badge">{item.status??"pending"}</span></summary><p className="ws-muted">{item.source}{item.actor?` · ${item.actor} · ${new Date(item.at!).toLocaleString()}`:""}</p><label htmlFor={controlId}>Assessment</label><select id={controlId} value={status} onChange={e=>setStatus(e.target.value)}><option value="pending">Pending</option><option value="done">Done · assessed by reviewer</option><option value="not_applicable">Not applicable</option></select><label>Evidence or reason<textarea maxLength={2000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Test run, rollout steps, recovery plan, or why this does not apply…"/></label><button className="ws-secondary" disabled={busy} onClick={()=>onSave(status,note)}>Save assessment</button></details>;
}
