"use client";
import {useEffect,useState} from "react";
import {stageLabels} from "@/workspace/model";
type Install={id:number;account:{login:string}};
type Repo={id:number;full_name:string;private:boolean};
type Pull={number:number;title:string;updated_at:string;draft:boolean;user:{login:string};head:{sha:string}};
type Review={id:string;pr_number:number;head_sha:string;created_at:number;findings:number;coverage:string;analyzedFiles:number};
type Job={id:string;pr_number:number;head_sha:string;status:string;stage:string;title:string};
async function json(url:string,options?:RequestInit){const response=await fetch(url,{cache:"no-store",...options});const body=await response.json();if(!response.ok)throw new Error(body.message??"The request could not finish.");return body;}
export function WorkspacePicker({installUrl}:{installUrl:string}){
 const [installs,setInstalls]=useState<Install[]>([]),[repos,setRepos]=useState<Repo[]>([]),[pulls,setPulls]=useState<Pull[]>([]),[reviews,setReviews]=useState<Review[]>([]),[jobs,setJobs]=useState<Job[]>([]);
 const [installation,setInstallation]=useState(""),[repository,setRepository]=useState(""),[preferredRepo,setPreferredRepo]=useState(""),[search,setSearch]=useState(""),[url,setUrl]=useState("");
 const [view,setView]=useState("inbox"),[automatic,setAutomatic]=useState(false),[automationReady,setAutomationReady]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[refresh,setRefresh]=useState(0);
 useEffect(()=>{setView(new URLSearchParams(location.search).get("view")??"inbox");},[]);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError("");json("/api/workspace",{signal:controller.signal}).then(body=>{setInstalls(body.installations);setAutomationReady(body.automationReady);const saved=body.preference;if(saved&&body.installations.some((item:Install)=>item.id===saved.installation_id)){setInstallation(String(saved.installation_id));setPreferredRepo(String(saved.repo_id));}else if(body.installations.length===1)setInstallation(String(body.installations[0].id));}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[]);
 useEffect(()=>{if(!installation)return;const controller=new AbortController();setLoading(true);json(`/api/workspace?installation=${installation}`,{signal:controller.signal}).then(body=>{setRepos(body.repositories);if(preferredRepo&&body.repositories.some((repo:Repo)=>String(repo.id)===preferredRepo))setRepository(preferredRepo);else if(body.repositories.length===1)setRepository(String(body.repositories[0].id));}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[installation,preferredRepo]);
 useEffect(()=>{if(!repository||!installation)return;const controller=new AbortController();let timer:ReturnType<typeof setTimeout>;async function load(){try{const body=await json(`/api/workspace?installation=${installation}&repository=${repository}`,{signal:controller.signal});setPulls(body.pulls);setReviews(body.reviews);setJobs(body.jobs);setAutomatic(body.automatic);if(body.jobs.some((job:Job)=>["queued","running"].includes(job.status)))timer=setTimeout(load,10000);}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:"Could not load reviews.");}finally{if(!controller.signal.aborted)setLoading(false);}}setLoading(true);setError("");load();json("/api/workspace/preferences",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({installation:Number(installation),repository:Number(repository)}),signal:controller.signal}).catch(()=>{});return()=>{controller.abort();clearTimeout(timer);};},[installation,repository,refresh]);
 async function start(pull:number,selection={installation:Number(installation),repository:Number(repository)}){setBusy(true);setError("");try{const body=await json("/api/workspace/review",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...selection,pull})});if(!/^\/workspace\/jobs\/[a-f0-9-]{36}$/.test(body.href))throw new Error("Unexpected review response.");location.assign(body.href);}catch(e){setError(e instanceof Error?e.message:"Could not start review.");setBusy(false);}}
 async function resolve(){setBusy(true);setError("");try{const selection=await json("/api/workspace/resolve",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url,installation:Number(installation)})});await start(selection.pull,selection);}catch(e){setError(e instanceof Error?e.message:"Could not find this PR.");setBusy(false);}}
 async function toggleAutomatic(){setBusy(true);setError("");try{await json("/api/workspace/preferences",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({installation:Number(installation),repository:Number(repository),automatic:!automatic})});setAutomatic(!automatic);}catch(e){setError(e instanceof Error?e.message:"Could not update automation.");}finally{setBusy(false);}}
 const filtered=pulls.filter(pr=>`${pr.number} ${pr.title} ${pr.user.login}`.toLowerCase().includes(search.toLowerCase()));
 const selectedRepo=repos.find(repo=>String(repo.id)===repository);
 return <><div className="ws-heading"><div><p className="ws-label">CONNECT THE DOTS BEFORE YOU SHIP</p><h1>{view==="history"?"Your review history.":view==="context"?"Know your repository.":"What needs your attention?"}</h1><p>A connected view of your changes, evidence, and next steps.</p></div><a className="ws-secondary" href={installUrl}>Manage repositories ↗</a></div>
 <div className="ws-repo-bar"><label>Account<select aria-label="GitHub account" value={installation} disabled={busy} onChange={e=>{setInstallation(e.target.value);setPreferredRepo("");setRepository("");setRepos([]);setPulls([]);setReviews([]);setJobs([]);}}><option value="">Choose account</option>{installs.map(i=><option key={i.id} value={i.id}>{i.account.login}</option>)}</select></label><label>Repository<select aria-label="Repository" value={repository} disabled={busy||!installation} onChange={e=>{setRepository(e.target.value);setPulls([]);setReviews([]);setJobs([]);}}><option value="">Choose repository</option>{repos.map(r=><option key={r.id} value={r.id}>{r.full_name}</option>)}</select></label><button className="ws-secondary" disabled={loading} onClick={()=>setRefresh(n=>n+1)}>Refresh</button></div>
 {error&&<div role="alert" className="ws-error">{error} <button onClick={()=>setRefresh(n=>n+1)}>Try again</button> <a href="/api/account/start">Reconnect GitHub</a></div>}
 <nav className="ws-tabs" aria-label="Repository views">{[["inbox","Review inbox"],["history","History"],["context","Repository context"]].map(([key,label])=><button key={key} aria-current={view===key?"page":undefined} onClick={()=>setView(key)}>{label}</button>)}</nav>
 {!loading&&!installs.length?<div className="ws-empty"><span className="ws-orbit">◉</span><h2>Your first connection starts here.</h2><p>Connect a public repository to discover what a change affects.</p><a className="clarity-start-button" href={installUrl}>Connect GitHub</a></div>:!repository?<div className="ws-empty"><h2>Choose a repository to begin.</h2><p>Your open pull requests and recent reviews will appear here.</p></div>:<>
 {view==="inbox"&&<><div className="ws-stats"><div><strong>{pulls.length}</strong><span>Open pull requests</span></div><div><strong>{new Set(reviews.map(r=>r.pr_number)).size}</strong><span>PRs reviewed recently</span></div><div><strong>{jobs.filter(j=>["queued","running"].includes(j.status)).length}</strong><span>Reviews in progress</span></div></div><form className="ws-url-form" onSubmit={e=>{e.preventDefault();resolve();}}><label htmlFor="pr-url">Have a pull request in mind?</label><div><input id="pr-url" type="url" placeholder="https://github.com/owner/repo/pull/123" value={url} onChange={e=>setUrl(e.target.value)} required/><button className="clarity-start-button" disabled={busy}>Review PR</button></div></form><div className="ws-panel"><div className="ws-panel-head"><h2>Open pull requests</h2><input aria-label="Search pull requests" placeholder="Search title, author, or number…" value={search} onChange={e=>setSearch(e.target.value)}/></div>{loading?<p role="status" className="ws-loading">Loading your GitHub workspace…</p>:filtered.length?filtered.map(pr=>{const review=reviews.find(r=>r.pr_number===pr.number),job=jobs.find(j=>j.pr_number===pr.number&&["queued","running"].includes(j.status));return <article className="ws-pr" key={pr.number}><div className="ws-pr-icon">{pr.draft?"◌":"⑂"}</div><div className="ws-pr-info"><a href={`https://github.com/${selectedRepo?.full_name}/pull/${pr.number}`} target="_blank" rel="noreferrer">{pr.title}</a><p>#{pr.number} · {pr.user.login} · {pr.draft?"Draft · ":""}Updated {new Date(pr.updated_at).toLocaleDateString()}</p></div><div className="ws-pr-status">{job?<a href={`/workspace/jobs/${job.id}`}>{stageLabels[job.stage]}</a>:review?<><span className={review.head_sha===pr.head.sha?"ws-badge":"ws-badge ws-stale"}>{review.head_sha===pr.head.sha?`${review.findings} observations`:"New commits · recheck"}</span><a href={`/workspace/reviews/${review.id}`}>Open report</a></>:<span className="ws-muted">Ready to review</span>}</div><button className="ws-secondary" disabled={busy||!!job} onClick={()=>start(pr.number)}>{review?"Recheck":"Review"}</button></article>}):<div className="ws-empty"><h3>{search?"No matching pull requests.":"No open pull requests yet."}</h3><p>{search?"Try another title or author.":"Open a pull request on GitHub, then refresh this inbox."}</p></div>}</div></>}
 {view==="history"&&<div className="ws-panel"><div className="ws-panel-head"><h2>Recent reviews</h2><span className="ws-muted">Available for 7 days</span></div>{reviews.length?reviews.map(r=><a className="ws-history-row" key={r.id} href={`/workspace/reviews/${r.id}`}><div><strong>Pull request #{r.pr_number}</strong><p>{r.head_sha.slice(0,8)} · {new Date(r.created_at).toLocaleString()}</p></div><span>{r.findings} observations</span><span className="ws-badge">{r.coverage} coverage</span><span>Open →</span></a>):<div className="ws-empty"><h3>Your review history will grow here.</h3><p>Start a review from your inbox.</p></div>}{jobs.filter(j=>j.status==="failed").map(j=><div key={j.id} className="ws-pr"><span>PR #{j.pr_number} · Review interrupted</span><button className="ws-secondary" disabled={busy} onClick={()=>start(j.pr_number)}>Retry review</button></div>)}</div>}
 {view==="context"&&<div className="ws-context-grid"><section className="ws-panel ws-padded"><p className="ws-label">CONNECTED REPOSITORY</p><h2>{selectedRepo?.full_name}</h2><p>NodeDots checks static JavaScript and TypeScript relationships, supported routes, environment references, schemas, and test imports.</p><dl className="ws-details"><div><dt>Latest reviewed scope</dt><dd>{reviews[0]?`${reviews[0].analyzedFiles} files · ${reviews[0].coverage} coverage`:"Run a review to establish coverage"}</dd></div><div><dt>Access</dt><dd>Selected GitHub installation</dd></div><div><dt>Execution</dt><dd>Source is read; repository code is never executed.</dd></div></dl><p className="ws-muted">Coverage belongs to each commit-pinned review. Dynamic behavior and external service state may remain unknown.</p></section><section className="ws-panel ws-padded"><p className="ws-label">YOUR SHIPPING WORKFLOW</p><h2>Review new commits automatically.</h2><p>Review new and updated pull requests, with an advisory GitHub check linking to the evidence. Your tests and human review remain essential.</p><button className="ws-secondary" role="switch" aria-checked={automatic} disabled={busy||(!automatic&&!automationReady)} onClick={toggleAutomatic}>{automatic?"Automatic reviews on · Turn off":"Enable automatic reviews"}</button>{!automationReady&&<p className="ws-muted">App signing and webhook setup are required before automatic reviews can be enabled.</p>}<p className="ws-muted">A repository administrator or maintainer must enable this setting.</p></section></div>}
 </>}
 <p className="ws-footnote">Evidence first. Advisory reviews. Coverage and uncertainty remain visible in every report.</p></>;
}
