"use client";
import {useEffect,useState} from "react";
import type {ImpactReport,Finding} from "@/engine/types";
import {ShippingReview} from "@/components/shipping-workflow";
import {findings} from "@/workspace/model";
type Decision={disposition:string;reason:string|null;created_at:number};
type Props={id:string;report:ImpactReport;repository:string;pull:number;head:string;base:string;installation:number;repoId:number;stale:boolean;compare:{new:number;persisting:number;noLongerObserved:number}|null};
function RelationshipMap({report,selected,onPath}:{report:ImpactReport;selected:Finding|undefined;onPath:(path:string)=>void}){
 const selectedPaths=new Set(selected?.evidence.map(e=>e.path)??[]);
 const paths=[...new Set([...report.changed.map(e=>e.path),...report.affected.flatMap(e=>e.via)])].slice(0,24);
 const edges=[...new Set(report.affected.flatMap(e=>e.via.slice(1).map((path,i)=>JSON.stringify([e.via[i],path]))))].map(e=>JSON.parse(e) as [string,string]).filter(([a,b])=>paths.includes(a)&&paths.includes(b));
 const width=620,height=Math.max(250,Math.ceil(paths.length/3)*105+30);
 const point=(i:number)=>({x:110+(i%3)*200,y:55+Math.floor(i/3)*105});
 return <div className="ws-map"><div className="ws-map-legend"><span>● Changed</span><span>○ Affected</span><span>Selected evidence highlighted</span></div>{paths.length?<svg viewBox={`0 0 ${width} ${height}`} role="group" aria-label="Evidence-backed file relationships">{edges.map(([a,b])=>{const p=point(paths.indexOf(a)),q=point(paths.indexOf(b));return <path key={`${a}:${b}`} d={`M${p.x},${p.y} C${p.x},${(p.y+q.y)/2} ${q.x},${(p.y+q.y)/2} ${q.x},${q.y}`} fill="none" stroke="var(--line)" strokeWidth="2"/>;})}{paths.map((path,i)=>{const p=point(i),changed=report.changed.some(e=>e.path===path);return <g key={path} role="button" tabIndex={0} aria-label={`Inspect ${path}`} onClick={()=>onPath(path)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();onPath(path);}}}><title>{path}</title><rect x={p.x-88} y={p.y-28} width="176" height="56" rx="10" fill={selectedPaths.has(path)?"var(--ws-highlight)":"var(--surface)"} stroke={selectedPaths.has(path)?"#92ac38":"var(--line)"}/><circle cx={p.x-72} cy={p.y-3} r="4" fill={changed?"#92ac38":"var(--muted)"}/><text x={p.x-59} y={p.y} fill="var(--ink)" fontSize="11">{path.split("/").pop()?.slice(0,22)}</text><text x={p.x-59} y={p.y+14} fill="var(--muted)" fontSize="9">{changed?"Changed":"Affected"}</text></g>;})}</svg>:<div className="ws-empty">No supported relationships were established for this change.</div>}<p className="ws-muted">{paths.length===24?"Showing up to 24 files. ":""}Connections use the engine’s recorded impact paths. Unconnected evidence is shown in the inspector.</p></div>;
}
export function WorkspaceReview(props:Props){
 const {id,report,repository,pull,head,base}=props;
 const all=findings(report),[selectedId,setSelectedId]=useState(all[0]?.fingerprint??""),[filter,setFilter]=useState("all"),[tab,setTab]=useState("map"),[path,setPath]=useState(""),[decisions,setDecisions]=useState<Record<string,Decision>>({}),[reason,setReason]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[loaded,setLoaded]=useState(false);
 const [revision,setRevision]=useState(0);
 const selected=all.find(f=>f.fingerprint===selectedId),visible=all.filter(f=>filter==="all"||f.state===filter),decision=selected?decisions[selected.fingerprint]:undefined;
 useEffect(()=>{const controller=new AbortController();fetch(`/api/workspace/feedback/${id}`,{signal:controller.signal,cache:"no-store"}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.message);const view:Record<string,Decision>={};for(const event of body.events){if(event.disposition==="cleared")delete view[event.fingerprint];else view[event.fingerprint]=event;}setDecisions(view);setReason(view[selectedId]?.reason??"");setLoaded(true);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[id]);
 async function save(disposition:string){if(!selected)return;setBusy(true);setError("");try{const response=await fetch(`/api/workspace/feedback/${id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({fingerprint:selected.fingerprint,disposition,reason})});const body=await response.json();if(!response.ok)throw new Error(body.message);setRevision(n=>n+1);setDecisions(current=>{const next={...current};if(disposition==="cleared")delete next[selected.fingerprint];else next[selected.fingerprint]={disposition,reason,created_at:Date.now()};return next;});}catch(e){setError(e instanceof Error?e.message:"Could not save your decision.");}finally{setBusy(false);}}
 async function recheck(){setBusy(true);setError("");try{const response=await fetch("/api/workspace/review",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({installation:props.installation,repository:props.repoId,pull})});const body=await response.json();if(!response.ok)throw new Error(body.message);if(!/^\/workspace\/jobs\/[a-f0-9-]{36}$/.test(body.href))throw new Error("Invalid response.");location.assign(body.href);}catch(e){setError(e instanceof Error?e.message:"Could not recheck.");setBusy(false);}}
 function choose(finding:Finding){setSelectedId(finding.fingerprint);setReason(decisions[finding.fingerprint]?.reason??"");setPath("");}
 const open=all.filter(f=>!["dismissed","fixed","intentional"].includes(decisions[f.fingerprint]?.disposition??"")).length;
 return <><div className="ws-heading"><div><p className="ws-label">{repository} / PULL REQUEST #{pull}</p><h1>See the change. Follow the impact.</h1><p>{report.changed.length} changed files · {report.affected.length} affected files · {report.coverage.completeness} coverage</p></div><div className="ws-review-actions"><a className="ws-secondary" href={`https://github.com/${repository}/pull/${pull}`} target="_blank" rel="noreferrer">Open on GitHub ↗</a><button className="clarity-start-button" disabled={busy} onClick={recheck}>Recheck latest commit</button></div></div>
 {props.stale&&<div className="ws-notice">This PR has newer commits. This report describes {head.slice(0,8)}; recheck to review the latest change.</div>}
 {error&&<p role="alert" className="ws-error">{error}</p>}
 <section className="ws-review-summary"><div><span className="ws-label">REVIEW SUMMARY</span><h2>{all.length?`${open} observations to work through.`:"No findings in the checked scope."}</h2><p>{all.length?"Inspect the consequence, follow its evidence, and record your decision.":"Review the examined scope and unknowns before acting. This is not a guarantee of safety."}</p></div><div><span className="ws-badge">{report.coverage.analyzedFiles} files examined</span><span className="ws-badge">{report.unknown.length} unknown areas</span><code>{base.slice(0,8)} → {head.slice(0,8)}</code></div></section>
 {props.compare&&<div className="ws-comparison"><span>{props.compare.new} new observations</span><span>{props.compare.persisting} persisting</span><span>{props.compare.noLongerObserved} no longer observed</span><small>Compared with the previous reviewed commit. Disappearance does not establish a fix.</small></div>}
 <div className="ws-review-grid"><aside className="ws-findings ws-panel"><div className="ws-panel-head"><h2>Observations <span>{all.length}</span></h2></div><label className="ws-filter">Filter<select value={filter} onChange={e=>setFilter(e.target.value)}>{["all","MISSING","CONFLICTING","UNCERTAIN","ACTION_REQUIRED"].map(s=><option key={s} value={s}>{s==="all"?"All states":s.replace("_"," ").toLowerCase()}</option>)}</select></label><div className="ws-finding-list">{visible.map(f=><button key={f.fingerprint} aria-pressed={selectedId===f.fingerprint} disabled={!loaded} onClick={()=>choose(f)}><span className={`ws-state state-${f.state.toLowerCase()}`}>{f.state.replace("_"," ")}</span><strong>{f.title}</strong><small>{f.severity} severity · {decisions[f.fingerprint]?.disposition??"Not reviewed"}</small></button>)}{!visible.length&&<p className="ws-padded ws-muted">No observations in this view. Check coverage for the scope examined.</p>}</div></aside>
 <section className="ws-panel ws-review-centre"><nav className="ws-tabs" aria-label="Review views">{[["map","Impact map"],["scope","Scope & unknowns"],["checklist","Next steps"]].map(([key,label])=><button key={key} aria-current={tab===key?"page":undefined} onClick={()=>setTab(key)}>{label}</button>)}</nav>{tab==="map"?<RelationshipMap report={report} selected={selected} onPath={p=>{setPath(p);const finding=all.find(f=>f.evidence.some(e=>e.path===p));if(finding){setSelectedId(finding.fingerprint);setReason(decisions[finding.fingerprint]?.reason??"");}}}/>:tab==="scope"?<div className="ws-padded"><h2>What was checked</h2><p>{report.coverage.analyzedFiles} files analyzed; {report.coverage.changedFilesAnalyzed} changed files analyzed; {report.coverage.changedFilesIgnored} changed files ignored.</p>{report.coverage.notes.map((note,i)=><p key={i}>{note}</p>)}<h3>What remains unknown</h3>{report.unknown.length?report.unknown.map((u,i)=><div className="ws-scope-item" key={i}><strong>{u.category}</strong><p>{u.detail}</p><code>{u.paths.join(", ")}</code></div>):<p>No additional unknowns recorded. Only supported static relationships were examined.</p>}<h3>Skipped files</h3>{report.coverage.skippedFiles.map((f,i)=><p key={i}><code>{f.path}</code> · {f.reason}</p>)}</div>:<div className="ws-padded"><h2>Before you ship</h2>{report.checklist.length?<ol className="ws-checklist">{report.checklist.map((item,i)=><li key={i}>{item}</li>)}</ol>:<p>No additional checklist items were established. Keep your tests and human review.</p>}</div>}</section>
 <aside className="ws-inspector ws-panel ws-padded">{selected?<><p className={`ws-state state-${selected.state.toLowerCase()}`}>{selected.state.replace("_"," ")}</p><h2>{selected.title}</h2><p>{selected.explanation}</p><div className="ws-inspector-block"><h3>Evidence</h3>{selected.evidence.map((e,i)=><div key={i}><a href={`https://github.com/${repository}/blob/${e.baseSide?base:head}/${e.path.split("/").map(encodeURIComponent).join("/")}#L${e.startLine}-L${e.endLine}`} target="_blank" rel="noreferrer"><code>{e.path}:{e.startLine}{e.baseSide?" · base":""}</code> ↗</a><p>{e.note}</p></div>)}</div><div className="ws-inspector-block"><h3>Suggested next step</h3><p>{selected.nextStep}</p><details><summary>{selected.confidence.band} confidence · Why?</summary><p>{selected.confidence.explanation}</p><code>{selected.ruleId} · {selected.ruleVersion}</code></details></div><div className="ws-inspector-block"><h3>Your decision</h3><label>Reason <span className="ws-muted">(optional)</span><textarea maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Add context for your future self…"/></label><div className="ws-decisions">{["accepted","dismissed","fixed","intentional"].map(value=><button key={value} disabled={busy||!loaded} aria-pressed={decision?.disposition===value} onClick={()=>save(value)}>{value}</button>)}</div>{decision&&<><p role="status" className="ws-muted">Saved · {decision.disposition}. “Fixed” records your assessment.</p><button className="ws-text-button" disabled={busy} onClick={()=>save("cleared")}>Clear decision</button></>}</div></>:<><h2>Explore the checked scope.</h2><p>Select a file in the map, or open Scope & unknowns to see what the analysis established.</p></>}{path&&<div className="ws-inspector-block"><h3>Selected file</h3><code>{path}</code><p>{report.affected.find(e=>e.path===path)?.via.join(" → ")??"Directly changed file."}</p></div>}</aside></div>
 <ShippingReview id={id} report={report} repository={repository} pull={pull} revision={revision} installation={props.installation} repoId={props.repoId}/>
 <p className="ws-footnote">Commit-pinned evidence · Saved decisions · Reports available for 7 days · Advisory analysis</p></>;
}
