import {LegalPage} from "@/components/legal-page";
import {pageMetadata} from "@/lib/site-metadata";
export const metadata=pageMetadata("/terms","NodeDots Beta Terms","Usage responsibilities, repository authorization, advisory reports, and current beta limits.");
export default function Terms(){return <LegalPage path="/terms" title="Beta usage terms" intro="The responsibilities and limits that apply to the current NodeDots Code experience.">
 <h2>Use the service with authority</h2><p>Only connect repositories and organizations you are authorized to access and submit for analysis. Keep your GitHub account secure, select appropriate installation access, and follow your organization’s review and data-sharing rules. The hosted beta accepts public repositories.</p>
 <h2>What the service does</h2><p>NodeDots reads supported source relationships and pull request metadata to produce advisory impact reports. It may disclose partial, unsupported, or unknown scope. The service does not execute repository code, autonomously apply fixes, or merge changes. Automatic reviews require an explicit maintainer setting.</p>
 <h2>Your content and permissions</h2><p>Connecting a repository does not transfer ownership of your source to NodeDots. The service processes the source and metadata needed for the requested analysis and stores reports and workflow records as described in <a href="/privacy">Privacy</a>. Do not put credentials, secrets, or unrelated personal information in briefs, decision reasons, assessment notes, or exported handoffs.</p>
 <h2>Review before you act</h2><p>Reports can be incomplete or incorrect. No finding, empty report, confidence label, acknowledgment, or checklist assessment guarantees correctness, security, compliance, test coverage, or a safe deployment. You remain responsible for reviewing evidence, running tests, and making merge and shipping decisions.</p>
 <h2>Share deliberately</h2><p>Only the report owner can grant another GitHub user report access. Recipients also need current repository access through NodeDots. Treat copied or downloaded handoffs as sensitive snapshots and share them only with appropriate recipients. Revoking a grant does not recall an exported copy.</p>
 <h2>Acceptable use</h2><p>Do not bypass access controls, attempt to obtain another user’s tokens or reports, use the service for unauthorized repository access, or disrupt availability through abusive requests. Report suspected vulnerabilities through the <a href="/security">security reporting guidance</a> and stop testing if you encounter another person’s information.</p>
 <h2>Beta availability and leaving</h2><p>Features, supported patterns, and limits may change during development. This beta does not offer a paid subscription or a service-level guarantee. You can sign out, disable automatic reviews, remove selected repositories, or uninstall the GitHub App. Disconnecting stops access; retention and deletion behavior are described in Privacy.</p>
 <h2>Open source and hosted-service terms</h2><p>The repository’s <a href="/license">Apache 2.0 license</a> governs licensed source distribution and use. It is separate from these hosted-service usage rules. Commercial billing, liability allocation, dispute procedures, governing law, and a verified contracting operator have not been published for this beta.</p>
 </LegalPage>;}
